
server:
  port: 8081
  servlet:
    context-path: /coffee-shop

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/coffee_shop
    username: coffee_shop_dev
    password: coffee_shop_pwd
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    schemas: coffee_shop_dev
    baseline-on-migrate: true
    baseline-version: 1
    locations: classpath:db/migration

logging:
  level:
    org.flywaydb: DEBUG